from enum import IntEnum


class ResultCode(IntEnum):
    SUCCESS = 0
    WRONG_ANSWER = 1
    CPU_TIME_LIMIT_EXCEEDED = 2
    REAL_TIME_LIMIT_EXCEEDED = 3
    MEMORY_LIMIT_EXCEEDED = 4
    RUNTIME_ERROR = 5
    COMPILE_ERROR = 6
    SYSTEM_ERROR = -1


class ErrorCode(IntEnum):
    SUCCESS = 0
    UNKNOWN_ERROR = -1
    INVALID_CONFIG = 3
    ROOT_REQUIRED = 4
    RESOURCE_LIMIT_FAILED = 5
    DUP2_FAILED = 6
    SETUID_FAILED = 7
    EXEC_FAILED = 8
    FORK_FAILED = 9
    WAIT_FAILED = 10
